# Generated by Django 2.2.2 on 2019-07-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookgenre',
            name='name',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='moviegenre',
            name='name',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
