# Generated by Django 2.2.2 on 2019-07-21 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0002_auto_20190720_1801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookgenre',
            old_name='books_count',
            new_name='count',
        ),
        migrations.RenameField(
            model_name='moviegenre',
            old_name='movies_count',
            new_name='count',
        ),
    ]
