FROM continuumio/miniconda3:latest
EXPOSE 8000
WORKDIR /app 
COPY requirements.txt /app
COPY move_ml.sh /app
RUN pip install -r requirements.txt --no-cache-dir
RUN pip install nvtabular
RUN pip install celery kombu==4.6.7 vine==1.3.0
RUN apt update
RUN apt -y install redis
RUN pip install redis
RUN pip3 install torch --extra-index-url https://download.pytorch.org/whl/cpu
COPY . /app 
CMD ["python", "-m", "celery", "-A", "MediaRecommendationServer", "worker"]