version: "3"

services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379

  mrec-app-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    links:
      - redis
    depends_on:
      - celery

  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    links:
      - redis