# Generated by Django 2.2.2 on 2019-07-11 03:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0007_auto_20190701_1600'),
        ('ratings', '0004_auto_20190710_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movierating',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='movierating',
            name='rating_user',
        ),
        migrations.AlterModelOptions(
            name='movieratinguser',
            options={},
        ),
        migrations.RemoveField(
            model_name='bookratinguser',
            name='predictions',
        ),
        migrations.AddField(
            model_name='movieratinguser',
            name='movie_rating_ids',
            field=models.ManyToManyField(to='media.Movie'),
        ),
        migrations.AddField(
            model_name='movieratinguser',
            name='movie_ratings',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='bookratinguser',
            name='book_rating_ids',
            field=models.ManyToManyField(to='media.Book'),
        ),
        migrations.DeleteModel(
            name='MoviePrediction',
        ),
        migrations.DeleteModel(
            name='MovieRating',
        ),
    ]
