# Generated by Django 2.2.2 on 2019-07-11 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0007_auto_20190701_1600'),
        ('ratings', '0005_auto_20190711_0313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movieratinguser',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='movieratinguser',
            name='movie_rating_ids',
        ),
        migrations.RemoveField(
            model_name='movieratinguser',
            name='movie_ratings',
        ),
        migrations.CreateModel(
            name='MovieRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(default=0.0)),
                ('movie', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='media.Movie')),
                ('rating_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ratings', to='ratings.MovieRatingUser')),
            ],
            options={
                'ordering': ['movie'],
            },
        ),
        migrations.CreateModel(
            name='MoviePrediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction', models.FloatField(default=0.0)),
                ('movie', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='media.Movie')),
                ('rating_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='predictions', to='ratings.MovieRatingUser')),
            ],
            options={
                'ordering': ['prediction'],
            },
        ),
    ]
