# Generated by Django 2.2.2 on 2019-07-11 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0006_auto_20190711_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieprediction',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.Movie'),
        ),
        migrations.AlterField(
            model_name='movierating',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.Movie'),
        ),
    ]
