# Generated by Django 2.2.2 on 2019-07-11 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0007_auto_20190711_0546'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movieprediction',
            options={'ordering': ['prediction', 'prediction_user']},
        ),
        migrations.AlterModelOptions(
            name='movierating',
            options={'ordering': ['movie', 'rating_user']},
        ),
        migrations.RenameField(
            model_name='movieprediction',
            old_name='rating_user',
            new_name='prediction_user',
        ),
    ]
