# Generated by Django 2.2.2 on 2019-07-11 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0007_auto_20190701_1600'),
        ('ratings', '0008_auto_20190711_0551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookratinguser',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='bookratinguser',
            name='book_rating_ids',
        ),
        migrations.RemoveField(
            model_name='bookratinguser',
            name='book_ratings',
        ),
        migrations.CreateModel(
            name='BookRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(default=0.0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.Book')),
                ('rating_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ratings', to='ratings.BookRatingUser')),
            ],
            options={
                'ordering': ['book', 'rating_user'],
            },
        ),
        migrations.CreateModel(
            name='BookPrediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction', models.FloatField(default=0.0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.Book')),
                ('prediction_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='predictions', to='ratings.BookRatingUser')),
            ],
            options={
                'ordering': ['prediction', 'prediction_user'],
            },
        ),
    ]
