# Generated by Django 2.2.2 on 2019-07-11 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0013_auto_20190711_1606'),
        ('ratings', '0009_auto_20190711_0558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieprediction',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='movieprediction',
            name='prediction_user',
        ),
        migrations.AlterField(
            model_name='bookrating',
            name='rating_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ratings', to='userauth.BookUser'),
        ),
        migrations.AlterField(
            model_name='movierating',
            name='rating_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ratings', to='userauth.MovieUser'),
        ),
        migrations.DeleteModel(
            name='BookPrediction',
        ),
        migrations.DeleteModel(
            name='BookRatingUser',
        ),
        migrations.DeleteModel(
            name='MoviePrediction',
        ),
        migrations.DeleteModel(
            name='MovieRatingUser',
        ),
    ]
