# Generated by Django 4.1 on 2023-02-03 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookseries',
            options={'ordering': ['most_viewed']},
        ),
        migrations.AlterModelOptions(
            name='movieseries',
            options={'ordering': ['most_viewed']},
        ),
    ]
