# Generated by Django 4.1 on 2023-02-02 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieuser',
            name='embedding_id',
            field=models.IntegerField(default=0),
        ),
    ]
