# Generated by Django 4.1 on 2023-02-20 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_movieuser_embedding_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookuser',
            name='embedding_id',
            field=models.IntegerField(default=0),
        ),
    ]
