# Generated by Django 2.2.2 on 2019-08-04 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0010_book_work_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
                ('tmdb_id', models.IntegerField()),
                ('movies', models.ManyToManyField(to='media.Movie')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BookSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
                ('goodreads_id', models.IntegerField()),
                ('books', models.ManyToManyField(to='media.Book')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
