# Generated by Django 2.2.2 on 2019-08-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookseries',
            name='id',
        ),
        migrations.RemoveField(
            model_name='movieseries',
            name='id',
        ),
        migrations.AlterField(
            model_name='bookseries',
            name='goodreads_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='movieseries',
            name='tmdb_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
