# Generated by Django 2.2.2 on 2019-08-04 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0002_auto_20190804_1835'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookseries',
            options={},
        ),
        migrations.AlterModelOptions(
            name='movieseries',
            options={},
        ),
        migrations.AlterField(
            model_name='bookseries',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='movieseries',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
