# Generated by Django 2.2.2 on 2019-08-04 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0005_auto_20190804_2048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movieseries',
            options={'ordering': ['-avg_rating']},
        ),
        migrations.AddField(
            model_name='movieseries',
            name='avg_rating',
            field=models.FloatField(default=0.0),
        ),
    ]
