# Generated by Django 2.2.2 on 2019-08-04 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0011_movie_tmdb_id'),
        ('series', '0006_auto_20190804_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookseries',
            name='most_viewed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Most_Viewed', to='media.Book'),
        ),
    ]
