# Generated by Django 2.2.2 on 2019-08-04 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0011_movie_tmdb_id'),
        ('series', '0007_bookseries_most_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieseries',
            name='most_viewed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Most_Viewed', to='media.Movie'),
        ),
    ]
