# Generated by Django 2.2.2 on 2019-06-28 22:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=32)),
                ('genres', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), size=None)),
                ('year', models.PositiveSmallIntegerField()),
                ('goodreads_id', models.IntegerField(unique=True)),
                ('average_rating', models.FloatField()),
                ('image_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('genres', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None)),
                ('year', models.PositiveSmallIntegerField()),
                ('imdb_id', models.IntegerField(unique=True)),
                ('average_rating', models.FloatField()),
                ('image_url', models.URLField(null=True)),
            ],
        ),
    ]
