# Generated by Django 2.2.2 on 2019-06-29 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
    ]
