# Generated by Django 2.2.2 on 2019-07-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_auto_20190629_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='small_image_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='image_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
