# Generated by Django 4.1.3 on 2022-12-18 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0003_remove_book_real_user_remove_movie_real_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="book", name="goodbooks_id",),
    ]
