# Generated by Django 2.2.2 on 2019-07-12 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0007_auto_20190701_1600'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-average_rating', 'title']},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-average_rating', 'title']},
        ),
    ]
