# Generated by Django 2.2.2 on 2019-08-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0009_auto_20190803_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='work_id',
            field=models.IntegerField(default=0),
        ),
    ]
