apiVersion: v1
kind: PersistentVolume
metadata:
  name: movies-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "$(pwd)/model_store"