# Generated by Django 4.1.3 on 2022-11-19 20:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("author", models.CharField(max_length=200)),
                (
                    "genres",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50), size=None
                    ),
                ),
                ("year", models.IntegerField()),
                ("goodreads_id", models.IntegerField(unique=True)),
                ("work_id", models.IntegerField(default=0)),
                ("average_rating", models.FloatField(default=0.0)),
                ("num_watched", models.IntegerField(default=0)),
                ("image_url", models.URLField(null=True)),
                ("small_image_url", models.URLField(null=True)),
            ],
            options={"ordering": ["-average_rating", "-num_watched", "title"],},
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                (
                    "genres",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=20), size=None
                    ),
                ),
                ("year", models.PositiveSmallIntegerField()),
                ("imdb_id", models.IntegerField(unique=True)),
                ("tmdb_id", models.IntegerField(default=0)),
                ("average_rating", models.FloatField(default=0.0)),
                ("num_watched", models.IntegerField(default=0)),
                ("image_url", models.URLField(null=True)),
            ],
            options={"ordering": ["-average_rating", "-num_watched", "title"],},
        ),
    ]
