# Generated by Django 4.1.3 on 2022-12-03 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="real_user",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="real_user",
            field=models.BooleanField(default=True),
        ),
    ]
