# Generated by Django 4.1.3 on 2022-12-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0002_book_real_user_movie_real_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="book", name="real_user",),
        migrations.RemoveField(model_name="movie", name="real_user",),
        migrations.AddField(
            model_name="book",
            name="goodbooks_id",
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name="movie",
            name="movielens_id",
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name="movie", name="tmdb_id", field=models.IntegerField(default=-1),
        ),
    ]
