# Generated by Django 4.1 on 2023-01-26 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_remove_book_goodbooks_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-num_watched', '-average_rating', 'title']},
        ),
    ]
