# Generated by Django 4.1 on 2023-02-09 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_alter_movie_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='work_id',
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='num_pages',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='ratings_id',
            field=models.IntegerField(default=-1),
        ),
    ]
