# Generated by Django 4.1 on 2023-02-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0006_remove_book_work_id_book_description_book_num_pages_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-num_watched', '-average_rating', 'title']},
        ),
        migrations.RemoveField(
            model_name='book',
            name='ratings_id',
        ),
        migrations.AddField(
            model_name='book',
            name='work_id',
            field=models.IntegerField(default=0),
        ),
    ]
