# Generated by Django 2.2.2 on 2019-06-28 22:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='book_uid',
        ),
        migrations.RemoveField(
            model_name='user',
            name='movie_uid',
        ),
        migrations.AddField(
            model_name='user',
            name='book_rating_ids',
            field=models.ManyToManyField(to='media.Book'),
        ),
        migrations.AddField(
            model_name='user',
            name='book_ratings',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=[], size=None),
        ),
        migrations.AddField(
            model_name='user',
            name='movie_rating_ids',
            field=models.ManyToManyField(to='media.Movie'),
        ),
        migrations.AddField(
            model_name='user',
            name='movie_ratings',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=[], size=None),
        ),
    ]
