# Generated by Django 2.2.2 on 2019-06-29 21:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_auto_20190628_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='book_ratings',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='movie_ratings',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=list, size=None),
        ),
    ]
