# Generated by Django 2.2.2 on 2019-07-03 16:17

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0007_auto_20190701_1600'),
        ('userauth', '0003_auto_20190629_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='book_rating_ids',
        ),
        migrations.RemoveField(
            model_name='user',
            name='book_ratings',
        ),
        migrations.RemoveField(
            model_name='user',
            name='movie_rating_ids',
        ),
        migrations.RemoveField(
            model_name='user',
            name='movie_ratings',
        ),
        migrations.CreateModel(
            name='MovieRatingUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_ratings', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=list, size=None)),
                ('movie_rating_ids', models.ManyToManyField(to='media.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='BookRatingUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_ratings', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=list, size=None)),
                ('book_rating_ids', models.ManyToManyField(to='media.Book')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='book_uid',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.PROTECT, to='userauth.BookRatingUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='movie_uid',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.PROTECT, to='userauth.MovieRatingUser'),
            preserve_default=False,
        ),
    ]
