# Generated by Django 2.2.2 on 2019-07-03 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0005_auto_20190703_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='book_uid',
        ),
        migrations.RemoveField(
            model_name='user',
            name='movie_uid',
        ),
    ]
