# Generated by Django 2.2.2 on 2019-07-03 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0009_auto_20190703_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='movie_uid',
        ),
        migrations.AlterField(
            model_name='user',
            name='book_uid',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='userauth.MovieRatingUser'),
        ),
    ]
