# Generated by Django 2.2.2 on 2019-07-11 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0012_auto_20190703_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MovieUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='book_uid',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='userauth.BookUser'),
        ),
        migrations.AlterField(
            model_name='user',
            name='movie_uid',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='userauth.MovieUser'),
        ),
    ]
