# Generated by Django 2.2.2 on 2019-07-13 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0015_auto_20190712_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hash_id',
        ),
    ]
