# Generated by Django 4.1.3 on 2022-11-19 20:14

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MLModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cfmodel", picklefield.fields.PickledObjectField(editable=False)),
            ],
        ),
    ]
